# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: java-pool
  demands:
    - Agent.Name -equals java-agent
 

stages:
- stage: Build
  displayName: compile
  jobs:
    - job: compile
      steps:
        -  task: Maven@4
           inputs:
             azureSubscription: 'Azure subscription 1(1)(8d924bc3-7a13-47ee-9bfb-69b45fab07d4)'
             mavenPomFile: 'pom.xml'
             goals: 'compile'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: false

- stage: test
  displayName: test 

  jobs:
   - job: test
     steps:
       - task: Maven@4
         inputs:
           azureSubscription: 'Azure subscription 1(1)(8d924bc3-7a13-47ee-9bfb-69b45fab07d4)'
           mavenPomFile: 'pom.xml'
           goals: 'test'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false

- stage: 
  displayName: trivy_scan
  jobs:
    - job: trivy_scan
      steps:
         - task: CmdLine@2
           inputs:
             script: 'trivy fs --format table -o fs.html .'
        
- stage: 
  displayName: docker

  jobs:
  - job: BuildAndPush
    displayName: Build and Push

    steps:
      - task: CmdLine@2
        inputs:
          script: 'mvn package'

      - task: Docker@2
        inputs:
           containerRegistry: 'acr-conn'
           repository:  'classregistry'
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'

     
